### ISSUE TITLE
Bill Run Page

### ISSUE THREAD

**Issue by RPCJendev** [Jersey-Electricity-plc/jwissues#2]
The bill run page requires redesigning to look a lot nicer. If we can maybe abandon nice colours, if the cause, and have a status field or something like that?

**Comment by tscottjendev** [comment]
@RPCJendev can we discuss further.

**Comment by Belsey23** [comment]
@RPCJendev After our discussion I'm guessing this should be labelled with demo?

**Comment by RPCJendev** [comment]
> @RPCJendev After our discussion I'm guessing this should be labelled with demo?

Yes please,

**Comment by Belsey23** [comment]
@RPCJendev is the design sufficient for the demo?

**Comment by RPCJendev** [comment]
That's great @Belsey23
