### ISSUE TITLE
Field names require correct case and spacing in CLE page

### ISSUE THREAD

**Issue by RPCJendev** [Jersey-Electricity-plc/jwissues#4]
![image](https://github.com/Jersey-Electricity-plc/jwissues/assets/102970851/5fb46ebb-e953-4efe-ade6-5893c9c98649)

**Comment by Belsey23** [comment]
@RPCJendev this is driven by the Dimension (although it took me long enough to find that out!).

![image](https://github.com/Jersey-Electricity-plc/jwissues/assets/102967931/462bd675-1c8e-4ad0-9217-ee09039f72e2)

Updated now:
![image](https://github.com/Jersey-Electricity-plc/jwissues/assets/102967931/cab10ab4-5cdb-423a-bdae-75718a61d1fd)

Please close the issue if you're happy with this.

**Comment by Belsey23** [comment]
Corrected the other ones as well
![image](https://github.com/Jersey-Electricity-plc/jwissues/assets/102967931/676fe779-d602-416a-9840-58e27da86ee5)

**Comment by RPCJendev** [comment]
Thanking you
