### ISSUE TITLE
Till ID Environment

### ISSUE THREAD

**Issue by RPCJendev** [Jersey-Electricity-plc/jwissues#57]
Set up till 06.

My environment variable is set up 06 as per screenshot but I get an error message:

![image](https://github.com/Jersey-Electricity-plc/jwissues/assets/102970851/6d49cc58-a4c4-4b6e-b14c-ca7665ff7c08)

![image](https://github.com/Jersey-Electricity-plc/jwissues/assets/102970851/4ac0aee4-64e9-4c86-8c83-7add4a35300b)

**Comment by tscottjendev** [comment]
Yeah, we can't read environment variables in BC (cloud anyway).    We might have to assign it on the User Setup somewhere.

**Comment by tscottjendev** [comment]
Also, please include the "details" in any error reported by clicking the "Copy Details" link.

**Comment by RPCJendev** [comment]
Sorry, will do the Copy details in future.

Can we discuss the design issue around this as soon as we can then as payment process with tills is important? Thanks.

**Comment by tscottjendev** [comment]
A couple of thoughts

- Could use a single instance Codeunit to save the "environment" variable, then provide a function/page to set any "environment variables" like TillID to be used in the session.
- There is a way to create an proxy between local hardware and a web site (or Azure Function) and then can actively interrogate the local hardware, but this still requires the BC client to be told what proxy to connect to.  There is nothing, that I am aware of, that will allow the BC client to interrogate the local hardware without setting up some sort of connection in advance.

**Comment by tscottjendev** [comment]
What is the "purpose" of the environment variable?  We don't seem to be doing other hardware related functions with it.

**Comment by RPCJendev** [comment]
There is/was hardware functions in previous versions that would open till drawers.

The reason for knowing the till id is to know what the amount posted to a particular till is at the end of the day for balancing/cashing up. How could this be done in a different way? Be interesting to know how LS Retail handle such things as you would have thought they would have to deal with different tills.

Would it be possible, I wonder, to just allow a look up for the user to select which till they want to post the transactions against at the time of the process and having a default on a set up record if they didn't want to record against multiple tills.

**Comment by tscottjendev** [comment]
I have added logic to prompt for TillID if it is required.  The prompt allows the user to select the TillID.  The prompt will only occur once per session and the value saved.  The next session the user will have to select the TillID again.

Assuming this works well enough we will have to open a new discussion on how to handle this from design point of view.

**Comment by RPCJendev** [comment]
Not working for me:

Get this:

If requesting support, please provide the following details to help troubleshooting:

The Tills does not exist. Identification fields and values: Code=''

Internal session ID: 
d6061fae-a916-448c-aa28-9dd32081a656

Application Insights session ID: 
7443c2f5-4483-4b80-8538-c8b40f56b6a6

Client activity id: 
89129f42-6338-07d6-18f1-db1bf46b4fc9

Time stamp on error: 
2023-09-04T13:56:10.0707767Z

AL call stack: 
"JW Customer Payments"(Page 9096406).OnOpenPage(Trigger) line 4 - Jenworks by Jendev
"JW Customer Payments Mgt."(CodeUnit 9096410).FetchEntriesInToPOSFromCustomer line 23 - Jenworks by Jendev
"JW Utility Account Card"(Page 9096011)."Payment Process - OnAction"(Trigger) line 4 - Jenworks by Jendev
