### ISSUE TITLE
Till Card - Safe No. is linking to GL Account? Incorrect

### ISSUE THREAD

**Issue by RPCJendev** [Jersey-Electricity-plc/jwissues#7]
![image](https://github.com/Jersey-Electricity-plc/jwissues/assets/102970851/4c0229f9-bf6d-4d30-a148-72bc62bf440b)

**Comment by tscottjendev** [comment]
@RPCJendev take a look and see if this is fixed now.

**Comment by RPCJendev** [comment]
All tested and all okay, Please close.
