### ISSUE TITLE
Property - Create Change of Customer

### ISSUE THREAD

**Issue by Belsey23** [Jersey-Electricity-plc/jwissues#78]
I created a new Property, populated the Address Register No. and Owner Customer No.

When I click Create Change of Customer action, I get the following message, which doesn't make much sense.
![image](https://github.com/Jersey-Electricity-plc/jwissues/assets/102967931/5a0593cb-6882-4fd8-808a-47e2a1f29735)

**Comment by Belsey23** [comment]
This happened because there are no Service Location lines. Maybe a better error? Can you do a CoC if there are no Service Locations? @RPCJendev

**Comment by RPCJendev** [comment]
Yes there could be no service lines if just doing something that isn't a electricity input or water inlet. @Belsey23
