### ISSUE TITLE
LastPass link 

### ISSUE THREAD

**Issue by JendevSLEG** [Jersey-Electricity-plc/jwissues#83]
When creating a new customer, there is a more commands button in the  "Customer Number, Phone Number, Email & Bill-to Customer No" fields on the customer page. If you click on it, it take you to LastPass.

I had a look at existing customers and the link is still there.

It is also on the Address Register page on the Address field.

P.S I can't add any labels?

![image](https://github.com/Jersey-Electricity-plc/jwissues/assets/122997604/4e9ed609-7c77-413e-85c1-186d8c85af16)

**Comment by tscottjendev** [comment]
This is an artifact of LastPass and not related to BC.
