### ISSUE TITLE
Line size on "Bill Run View Lines"

### ISSUE THREAD

**Issue by JendevSLEG** [Jersey-Electricity-plc/jwissues#84]
From the bill run page if you click on "Lines" it takes you to the "Bill Run View Lines" page. Please can you have a look at the size of the line on this page as to big. I'll run through with you if you like.

**Comment by Belsey23** [comment]
@JendevSLEG please review and confirm fix implemented correctly

**Comment by JendevSLEG** [comment]
@Belsey23 looks perfect. Thank you
